{"name": "test_validLogin", "status": "broken", "statusDetails": {"message": "AttributeError: 'function' object has no attribute 'allureLogs'", "trace": "self = <tests.LoginTest.LoginTest testMethod=test_validLogin>\n\n    @pytest.mark.run(order=1)\n    def test_validLogin(self):\n>       cl.allureLogs(\"App Launched\")\nE       AttributeError: 'function' object has no attribute 'allureLogs'\n\nLoginTest.py:21: AttributeError"}, "start": 1739940964022, "stop": 1739940964022, "uuid": "0e2309db-dc1c-4aa7-96b6-66f5c9d788f6", "historyId": "6d485cd84f8cf430b8322063143bb42e", "testCaseId": "6d485cd84f8cf430b8322063143bb42e", "fullName": "LoginTest.LoginTest#test_validLogin", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "suite", "value": "LoginTest"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "Chinmayi"}, {"name": "thread", "value": "15112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "LoginTest"}]}